openapi: 3.1.0
info:
  title: Elara Agent Runtime API
  version: 0.1.0
paths:
  /health:
    get:
      operationId: health
      responses:
        "200":
          description: API health
          content:
            application/json:
              schema:
                type: object
                required: [status]
                properties:
                  status:
                    type: string
                    enum: [ok]
  /agent-runs/{agentRunId}/events:
    get:
      operationId: replayAgentRunEvents
      parameters:
        - in: path
          name: agentRunId
          required: true
          schema:
            type: string
        - in: query
          name: lastSeq
          required: false
          schema:
            type: integer
            minimum: 0
      responses:
        "200":
          description: Ordered replay window
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AgentRunEvent"
components:
  schemas:
    AgentRunEvent:
      type: object
      required: [agentRunId, seq, eventType, payload]
      properties:
        agentRunId:
          type: string
        seq:
          type: integer
          minimum: 1
        eventType:
          type: string
        payload:
          type: object
          additionalProperties: true
